version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_office
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: office_db

volumes:
  mongo_data: